apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent-deploy
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-agent-deploy
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "statefulsets", "pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "update", "create", "patch", "apply"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-agent-deploy
subjects:
- kind: ServiceAccount
  name: jenkins-agent-deploy
  namespace: jenkins
roleRef:
  kind: ClusterRole
  name: jenkins-agent-deploy
  apiGroup: rbac.authorization.k8s.io