apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: monitoring-test
kubeadmConfigPatches:
- |-
  kind: ClusterConfiguration
  # configure controller-manager bind address
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0 #Disable localhost binding
      secure-port: "0"      #Disable the https 
  # configure etcd metrics listen address
  etcd:
    local:
      extraArgs:
        listen-metrics-urls: http://0.0.0.0:2381
  # configure scheduler bind address
  scheduler:
    extraArgs:
      bind-address: 0.0.0.0  #Disable localhost binding
      secure-port: "0"       #Disable the https
- |-
  kind: KubeProxyConfiguration
  # configure proxy metrics bind address
  metricsBindAddress: 0.0.0.0
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker